### ISSUE TITLE
Binary data should be passed through a byte pointer, not char

### ISSUE THREAD

**Issue by SukkoPera** [boseji/rBASE64#1]
The `input` parameter of the encoding function should be of type `byte *` rather than `char *`.

Ditto for the `output` parameter of the decoding function.

**Comment by boseji** [comment]
In general most of the function create at char * rather than byte *.
If one also check the converted output for stings in many platforms it is const char * hence the convention. 

Please justify the change.

**Comment by SukkoPera** [comment]
BASE64 is used to convert binary data to/from ASCII strings.

The usage of a char pointer for binary data is historical, because there was no other widely available type for 8-bit data. C99 introduced the uint8_t data type, which is more suited for this purpose. char somehow implies that the pointed data is ASCII, which is not in this case. Besides that, it is neither signed nor unsigned, which can lead to problems.

However this is an Arduino library, so it should respect the Arduino API, which has a byte type (which is roughly equivalent to uint8_t anyway), so it is probably the best choice in this case.

Just my 2 cents.

**Comment by boseji** [comment]
Sure we can do this, however I am out of time on this due to other priority projects.

Please feel free to make a pull request with correction you would like.
